"""Serialize packed frames to TexturePacker JSON Hash, plus a TS key union.

JSON Hash is what Phaser 3's `load.atlas` and PixiJS's `Assets.load` both read
without configuration, so no runtime adapter is needed.
"""

from __future__ import annotations

import json
from pathlib import Path

from .pack import Frame

APP = "ddalggak asset-pipeline"


def to_json_hash(frames: list[Frame], atlas_size: tuple[int, int],
                 image_name: str = "atlas.png") -> dict:
    entries = {}
    for f in frames:
        trimmed = (f.rect.w, f.rect.h) != f.source
        entries[f.name] = {
            "frame": {"x": f.rect.x, "y": f.rect.y, "w": f.rect.w, "h": f.rect.h},
            "rotated": False,
            "trimmed": trimmed,
            # where the trimmed pixels belong inside the original canvas
            "spriteSourceSize": {
                "x": f.offset[0], "y": f.offset[1], "w": f.rect.w, "h": f.rect.h,
            },
            "sourceSize": {"w": f.source[0], "h": f.source[1]},
            "pivot": {"x": 0.5, "y": 0.5},
        }

    return {
        "frames": entries,
        "meta": {
            "app": APP,
            "version": "1.0",
            "image": image_name,
            "format": "RGBA8888",
            "size": {"w": atlas_size[0], "h": atlas_size[1]},
            "scale": "1",
        },
    }


def write(frames: list[Frame], atlas_size: tuple[int, int], out_dir: Path,
          image_name: str = "atlas.png") -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "atlas.json"
    path.write_text(json.dumps(to_json_hash(frames, atlas_size, image_name),
                               indent=2, sort_keys=True) + "\n")
    return path


def to_animations(anims: list[dict], texture: str = "game") -> dict:
    """Phaser `anims.fromJSON` payload: one animation per multi-frame asset."""
    return {
        "anims": [
            {
                "key": a["key"],
                "type": "frame",
                "frames": [{"key": texture, "frame": name} for name in a["frames"]],
                "frameRate": a["fps"],
                "repeat": a["repeat"],
            }
            for a in anims
        ],
        "globalTimeScale": 1,
    }


def write_animations(anims: list[dict], out_dir: Path, texture: str = "game") -> Path | None:
    """Written only when something is actually animated — an empty file is noise."""
    if not anims:
        path = out_dir / "animations.json"
        path.unlink(missing_ok=True)
        return None
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "animations.json"
    path.write_text(json.dumps(to_animations(anims, texture), indent=2) + "\n")
    return path


def write_types(frames: list[Frame], out_dir: Path) -> Path:
    """A frame-key union so a typo in a sprite name is a compile error."""
    keys = "\n".join(f"  | {json.dumps(f.name)}" for f in frames)
    path = out_dir / "atlas.d.ts"
    path.write_text(
        "// Generated by asset-pipeline. Do not edit.\n"
        "export type AtlasFrame =\n" + keys + ";\n"
    )
    return path


def write_anim_types(anims: list[dict], out_dir: Path) -> None:
    """Append an AnimKey union next to AtlasFrame, when there are animations."""
    if not anims:
        return
    path = out_dir / "atlas.d.ts"
    keys = "\n".join(f"  | {json.dumps(a['key'])}" for a in anims)
    path.write_text(path.read_text() + "\nexport type AnimKey =\n" + keys + ";\n")
